// js/config.js
// Production v5.5 - 修正語法與變數對應 (window.AppConfig)

window.AppConfig = {
    // 1. 職業結構 (對應 app.js 的 JOB_STRUCTURE)
    JOB_STRUCTURE: {
        "騎士": ["龍", "敏爆", "其他"],
        "十字軍": ["坦", "輸出", "其他"],
        "鐵匠": ["戰鐵", "鍛造", "其他", "一般"],
        "煉金": ["一般", "其他"],
        "獵人": ["鳥", "陷阱", "AD", "其他"],
        "詩人": ["輔助", "輸出", "一般", "其他"],
        "舞孃": ["輔助", "輸出", "一般", "其他"],
        "神官": ["讚美", "驅魔", "暴牧", "其他"],
        "武僧": ["連技", "阿修", "一般", "其他"],
        "巫師": ["隕石", "冰雷", "其他"],
        "賢者": ["輔助", "法系", "一般", "其他"],
        "刺客": ["敏爆", "毒", "雙刀", "一般", "其他"],
        "流氓": ["脫裝", "輸出", "弓", "其他"],
        "槍手": ["一般", "其他"],
        "法師": ["隕石", "冰雷", "念", "其他"],
        "初心者": ["超級初心者", "其他"],
        "待定": ["待定"]
    },

    // 2. Firebase 設定
    FIREBASE_CONFIG: {
        apiKey: "AIzaSyCxVEcgftiu7qmHhgLV-XaLzf6naBhaf-k",
        authDomain: "ro123-aae1e.firebaseapp.com",
        projectId: "ro123-aae1e",
        storageBucket: "ro123-aae1e.firebasestorage.app",
        messagingSenderId: "401692984816",
        appId: "1:401692984816:web:711dacb2277b52fb7d0935",
        measurementId: "G-SVYZGQZB83"
    },

    // 3. 職業樣式 (app.js 顯示顏色必須)
    JOB_STYLES: [
        { key: ['騎士'], class: 'bg-job-knight', icon: 'fa-shield-alt' },
        { key: ['十字軍'], class: 'bg-job-crusader', icon: 'fa-shield-alt' },
        { key: ['神官'], class: 'bg-job-priest', icon: 'fa-cross' },
        { key: ['武僧'], class: 'bg-job-monk', icon: 'fa-fist-raised' },
        { key: ['巫師'], class: 'bg-job-wizard', icon: 'fa-hat-wizard' },
        { key: ['賢者'], class: 'bg-job-sage', icon: 'fa-book' },
        { key: ['法師'], class: 'bg-job-wizard', icon: 'fa-hat-wizard' },
        { key: ['獵人'], class: 'bg-job-hunter', icon: 'fa-bullseye' },
        { key: ['詩人'], class: 'bg-job-bard', icon: 'fa-music' },
        { key: ['舞孃'], class: 'bg-job-dancer', icon: 'fa-music' },
        { key: ['槍手'], class: 'bg-job-gunslinger', icon: 'fa-crosshairs' },
        { key: ['鐵匠'], class: 'bg-job-blacksmith', icon: 'fa-hammer' },
        { key: ['煉金'], class: 'bg-job-alchemist', icon: 'fa-flask' },
        { key: ['刺客'], class: 'bg-job-assassin', icon: 'fa-user-ninja' },
        { key: ['流氓'], class: 'bg-job-rogue', icon: 'fa-mask' },
        { key: ['初心者', '待定'], class: 'bg-job-default', icon: 'fa-user' }
    ],

    // 4. 初始成員資料 (原 initialMembers，改名並格式化以配合 app.js)
    SEED_DATA: [
        { id: "m01", gameName: "YT清燉小羔羊", lineName: "poppy🐶", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "會長", intro: "公會唯一清流 出淤泥而不染" },
        { id: "m02", gameName: "沐沐", lineName: "#Yuan", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "資料管理員", intro: "" },
        { id: "m03", gameName: "孤芳自賞", lineName: "Lam 🦄", baseJob: "獵人", subJob: "陷阱", role: "輸出", rank: "成員", intro: "" },
        { id: "m04", gameName: "小櫻花", lineName: "alan", baseJob: "武僧", subJob: "一般", role: "輔助", rank: "成員", intro: "待領養孤兒" },
        { id: "m05", gameName: "去去彈匣清空", lineName: "董宜坤", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "" },
        { id: "m06", gameName: "恐龍跌倒", lineName: "阿智", baseJob: "獵人", subJob: "鳥", role: "待定", rank: "成員", intro: "待領養孤兒" },
        { id: "m07", gameName: "襪子髒髒", lineName: "佳慶", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "" },
        { id: "m08", gameName: "魅力四射", lineName: "騰億", baseJob: "獵人", subJob: "鳥", role: "待定", rank: "成員", intro: "" },
        { id: "m09", gameName: "沐瑀", lineName: "Xian", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m10", gameName: "貓二", lineName: "咘小欣", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m11", gameName: "奕雲", lineName: "奕雲", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m12", gameName: "崔月月", lineName: "宇", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "" },
        { id: "m13", gameName: "魔魂大白鯊", lineName: "宏", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "" },
        { id: "m14", gameName: "貝席兒", lineName: "🐬", baseJob: "煉金", subJob: "一般", role: "待定", rank: "成員", intro: "待領養孤兒" },
        { id: "m15", gameName: "渺渺喵", lineName: "賀", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m16", gameName: "馬爾科姆", lineName: "鄒昀諭YunYuZou", baseJob: "獵人", subJob: "鳥", role: "待定", rank: "成員", intro: "5678不同爸爸" },
        { id: "m17", gameName: "香菜佐黑輪", lineName: "黑輪呦", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m18", gameName: "棨棨", lineName: "Peng", baseJob: "十字軍", subJob: "坦", role: "坦", rank: "成員", intro: "Здравствуйте ! как дела ?" },
        { id: "m19", gameName: "開喜婆婆", lineName: "江承峻", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m20", gameName: "FeiFei ", lineName: "妃Fei ", baseJob: "法師", subJob: "隕石", role: "輸出", rank: "成員", intro: "" },
        { id: "m21", gameName: "卉香", lineName: "古銘", baseJob: "刺客", subJob: "敏爆", role: "輸出", rank: "成員", intro: "" },
        { id: "m22", gameName: "傑森七七", lineName: "傑森", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "" },
        { id: "m23", gameName: "陳小圻", lineName: "陳嘉圻", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "大白鯊的朋友" },
        { id: "m24", gameName: "藤井樹", lineName: "Leo", baseJob: "法師", subJob: "隕石", role: "輸出", rank: "成員", intro: "" },
        { id: "m25", gameName: "妞妞甜八寶", lineName: "小涵", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "大白鯊的母奶" },
        { id: "m26", gameName: "", lineName: "星野悠（ホシノユウ）", baseJob: "鐵匠", subJob: "一般", role: "待定", rank: "成員", intro: "" },
        { id: "m27", gameName: "YT泰愛玩遊戲直bo", lineName: "浩", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "" },
        { id: "m28", gameName: "六六", lineName: "六六", baseJob: "十字軍", subJob: "坦", role: "坦", rank: "成員", intro: "" },
        { id: "m29", gameName: "大雄", lineName: "灬森灬", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "待領養孤兒" },
        { id: "m30", gameName: "貓璃", lineName: "陳小貓", baseJob: "刺客", subJob: "一般", role: "輸出", rank: "成員", intro: "睡神無敵朋友" },
        { id: "m31", gameName: "迪卡普歐", lineName: "pei.yu.yang", baseJob: "鐵匠", subJob: "一般", role: "待定", rank: "成員", intro: "睡神無敵麻吉" },
        { id: "m32", gameName: "睡神無敵", lineName: "A-Wei 黃執維", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "睡神就是無敵" },
        { id: "m33", gameName: "牧牧", lineName: "阿揚", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "待領養孤兒" },
        { id: "m34", gameName: "莫忘中出", lineName: "徐小宏🖖🏼", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "" },
        { id: "m35", gameName: "極度", lineName: "Wang", baseJob: "法師", subJob: "念", role: "輸出", rank: "成員", intro: "" },
        { id: "m36", gameName: "水鏡是條狗", lineName: "Ryan", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m37", gameName: "新竹房仲兩廣", lineName: "兩廣寬", baseJob: "賢者", subJob: "一般", role: "輔助", rank: "成員", intro: "" },
        { id: "m38", gameName: "HsuBoBo", lineName: "富邦-Shawn(小逸)", baseJob: "刺客", subJob: "敏爆", role: "輸出", rank: "成員", intro: "" },
        { id: "m39", gameName: "該獵戶已夜梟", lineName: "成成", baseJob: "獵人", subJob: "鳥", role: "待定", rank: "成員", intro: "待領養孤兒" },
        { id: "m40", gameName: "歐洲獨角獸", lineName: "魏駿翔", baseJob: "流氓", subJob: "輸出", role: "待定", rank: "成員", intro: "" },
        { id: "m41", gameName: "水蜜桃王", lineName: "Louie", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "櫻花表弟" },
        { id: "m42", gameName: "潘朵拉企鵝", lineName: "Keith-匠屋空間工作室", baseJob: "流氓", subJob: "脫裝", role: "輸出", rank: "成員", intro: "待領養孤兒, 我喜歡大叔" },
        { id: "m43", gameName: "白非羽", lineName: "明", baseJob: "槍手", subJob: "一般", role: "輔助", rank: "成員", intro: "待領養孤兒" },
        { id: "m44", gameName: "Weilin", lineName: "中古車採購 威霖", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m45", gameName: "蝸牛丶", lineName: "江", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "" },
        { id: "m46", gameName: "三十九度八", lineName: "ZhenYun", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "待領養孤兒" },
        { id: "m47", gameName: "提摩丶", lineName: "小寶", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "待領養孤兒" },
        { id: "m48", gameName: "珮可", lineName: "張誌恒", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "待領養孤兒" },
        { id: "m49", gameName: "哈啾", lineName: "哈啾", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "哈啾本哈" },
        { id: "m50", gameName: "長歌恨", lineName: "丫鵬", baseJob: "獵人", subJob: "鳥", role: "待定", rank: "成員", intro: "" },
        { id: "m51", gameName: "嘎拉", lineName: "Agera", baseJob: "騎士", subJob: "敏爆", role: "待定", rank: "成員", intro: "待領養孤兒" },
        { id: "m52", gameName: "老婆幫我儲一單", lineName: "許竣凱", baseJob: "十字軍", subJob: "坦", role: "坦", rank: "成員", intro: "" },
        { id: "m53", gameName: "冬天君", lineName: "Wei", baseJob: "獵人", subJob: "鳥", role: "坦", rank: "成員", intro: "待領養孤兒" },
        { id: "m54", gameName: "啤酒香煙法力無邊", lineName: "Randy", baseJob: "十字軍", subJob: "坦", role: "坦", rank: "成員", intro: "" },
        { id: "m55", gameName: "批星戴月", lineName: "隆", baseJob: "刺客", subJob: "毒", role: "輸出", rank: "成員", intro: "大白鯊的朋友" },
        { id: "m56", gameName: "139", lineName: "汪", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "" },
        { id: "m57", gameName: "靈刀灰休", lineName: "Jimmy Chou", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m58", gameName: "陳冠希", lineName: "gary", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "大白鯊的朋友" },
        { id: "m59", gameName: "南門小皮", lineName: "Eric", baseJob: "刺客", subJob: "敏爆", role: "輸出", rank: "成員", intro: "" },
        { id: "m60", gameName: "Lucia", lineName: "", baseJob: "刺客", subJob: "敏爆", role: "輸出", rank: "成員", intro: "" },
        { id: "m61", gameName: "冷炩兒", lineName: "恩蓉MoMo", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m62", gameName: "貓窩下的星空", lineName: "GcJie", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "待領養孤兒" },
        { id: "m63", gameName: "青川", lineName: "Sean Liou", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "" },
        { id: "m64", gameName: "初蕾丶", lineName: "🐰", baseJob: "神官", subJob: "讚美", role: "輔助", rank: "成員", intro: "" },
        { id: "m65", gameName: "碧空炎冰", lineName: "阿賢", baseJob: "槍手", subJob: "一般", role: "輸出", rank: "成員", intro: "" },
        { id: "m66", gameName: "熊熊很大", lineName: "仲軒", baseJob: "法師", subJob: "隕石", role: "輸出", rank: "成員", intro: "" },
        { id: "m67", gameName: "小波", lineName: "航", baseJob: "獵人", subJob: "鳥", role: "輸出", rank: "成員", intro: "" },
        { id: "m68", gameName: "Pogin", lineName: "Pogin", baseJob: "詩人", subJob: "一般", role: "輔助", rank: "成員", intro: "待領養孤兒, 哈啾老公" },
        { id: "m69", gameName: "", lineName: "咩假屁謀", baseJob: "待定", subJob: "待定", role: "待定", rank: "成員", intro: "" },
        { id: "m70", gameName: "果仔", lineName: "廖琮昱", baseJob: "賢者", subJob: "一般", role: "待定", rank: "成員", intro: "" },
        { id: "m71", gameName: "daliesi", lineName: "鍾豐年", baseJob: "刺客", subJob: "毒", role: "輔助", rank: "成員", intro: "" },
        { id: "m72", gameName: "星夜", lineName: "蔡家昕", baseJob: "刺客", subJob: "毒", role: "輸出", rank: "成員", intro: "睡神無敵小弟" },
        { id: "m73", gameName: "狗是水鏡", lineName: "NICK", baseJob: "流氓", subJob: "輸出", role: "輸出", rank: "成員", intro: "" }
    ].map(m => ({
        // 自動合併資料
        id: m.id,
        gameName: m.gameName,
        lineName: m.lineName,
        mainClass: (m.mainClass) ? m.mainClass : `${m.baseJob}(${m.subJob})`, 
        role: m.role,
        rank: m.rank,
        intro: m.intro
    })),
    
    // 5. 預留欄位
    SEED_GROUPS: [],
    SEED_ACTIVITIES: []
};